AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Demo CloudFront Distribution.
  Managed by dev-platform

Parameters:
  Environment:
    Description: The name of the environment to deploy to.
    Type: String
    AllowedPattern: ((production)|(integration)|(staging)|(build)|(dev))

Mappings:
  EnvironmentConfiguration:
    "dev":
      CloudfrontCertificate: "arn:aws:acm:us-east-1:842766856468:certificate/9f90373b-46f9-4808-918c-16ae49943e7b"

Resources:

  CloudfrontDistribution:
    #checkov:skip=CKV_AWS_86: No Access Logs setup is required
    #checkov:skip=CKV_AWS_68: No WAF is required
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "cloudfront-estimate.${Environment}.platform.sandpit.account.gov.uk"
        Origins:
          - DomainName:
              Fn::ImportValue:
                Fn::Sub: "DefaultApiDomainName-${Environment}"
            OriginPath:
              Fn::ImportValue:
                Fn::Sub: "DefaultApiStage-${Environment}"
            Id: RestAPIGatewayOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'
              OriginSSLProtocols:
                - TLSv1.2
        Enabled: 'true'
        Comment: CloudfrontToRestAPI
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad #Managed-CachingDisabled
          TargetOriginId: RestAPIGatewayOrigin
          OriginRequestPolicyId: 33f36d7e-f396-46d9-90e0-52428a34d9dc #Managed-AllViewerAndCloudFrontHeaders-2022-06
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !ImportValue CloudfrontTICFFunctionArn
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
          AcmCertificateArn: !FindInMap [ EnvironmentConfiguration, !Ref Environment,  CloudfrontCertificate ]

Outputs:
  CloudfrontDistDomain:
    Description: Default distribution domain name
    Value: !GetAtt CloudfrontDistribution.DomainName
    Export:
      Name: !Sub "CloudfrontDistDomain-${Environment}"
