AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Demo CloudFront Distribution.
  Managed by dev-platform

Resources:
  FraudHeadersFunction:
    Type: AWS::CloudFront::Function
    Properties:
      AutoPublish: true
      FunctionCode: |
        async function handler(event) {
          const request = event.request;
          const headers = request.headers;
          const txmaHeader = {};

          txmaHeader.timestamp = Date.now();
          if("cloudfront-viewer-ja3-fingerprint" in headers){
            txmaHeader.ja3Fingerprint = headers['cloudfront-viewer-ja3-fingerprint'];
          }
          if("cloudfront-viewer-address" in headers){
            txmaHeader.ipAddressPort = headers['cloudfront-viewer-address'];
          }
          if("cloudfront-viewer-country" in headers){
            txmaHeader.countryCode = headers['cloudfront-viewer-country'];
          }
          if("user-agent" in headers){
            txmaHeader.userAgent = headers['user-agent'];
          }
          if("accept-encoding" in headers){
            txmaHeader.acceptLanguage = headers['accept-language'];
          }

          headers['txma-audit-encoded'] = {value: btoa(JSON.stringify(txmaHeader)) };
          return request;
        }
      FunctionConfig:
        Comment: Add TICF fraud headers
        Runtime: cloudfront-js-2.0
      Name: "TiCFFraudHeadersFunction"

Outputs:
  CloudfrontTICFFuncArn:
    Description: Cloudfront TICF Function Arn
    Value: Fn::GetAtt GetAtt FraudHeadersFunction.FunctionMetadata.FunctionARN
    Export:
      Name: CloudFrontTICFFunctionArn

