AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creating SSM parameters based on ENVs using cloudformation mapping.
  Managed by dev-platform

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - build
      - staging
      - production
      - local

  LocalName:
    Description: Unique name component used in ephemeral deploys
    Type: String
    Default: ""

  LocalBasicParameterValue:
    Description: Override of the BasicParameterValue for ephemeral deploy
    Type: String
    Default: "local"

Rules:
  LocalNameRequiredForLocalEnvironment:
    RuleCondition: !Equals [ !Ref Environment, "local" ]
    Assertions:
      - Assert: !Not [ !Equals [ !Ref LocalName, "" ] ]
        AssertDescription: >
          Must specify LocalName when Environment is "local"

  LocalNameEmptyForNonLocalEnvironment:
    RuleCondition: !Not [ !Equals [ !Ref Environment, "local" ] ]
    Assertions:
      - Assert: !Equals [ !Ref LocalName, "" ]
        AssertDescription: >
          Must not specify LocalName when Environment is not "local"

Conditions:
  IsLocal:
    Fn::Not:
      - Fn::Equals:
          - !Ref Environment
          - "local"

Mappings:
  BasicParameterValue:
    Environment:
      staging: "staging"
      production: "production"
      local: "unused"

  AnotherBasicParameterValue:
    Environment:
      staging: "this-is-staging"
      production: "this-is-production"
      local: "this-is-local"

Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Environment}${LocalName}/BasicParameter"
      Type: String
      Value: !If
        - IsLocal
        - !Ref LocalBasicParameterValue
        - !FindInMap [BasicParameterValue, Environment, !Ref Environment]
      AllowedPattern: "^[a-zA-Z]+$"
      Tags:
        Product: GOV.UK Sign In
        System: Dev Platform
        Environment: Demo
        Service: backend
        Name: BasicParameter
        Source: alphagov/di-devplatform-demo-sam-app/parameters/template.yaml


  AnotherBasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Environment}${LocalName}/AnotherBasicParameter"
      Type: String
      Value: !FindInMap [AnotherBasicParameterValue, Environment, !Ref Environment]
      Tags:
        Product: GOV.UK Sign In
        System: Dev Platform
        Environment: Demo
        Service: backend
        Name: AnotherBasicParameter
        Source: alphagov/di-devplatform-demo-sam-app/parameters/template.yaml

