AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creating SSM parameters based on ENVs using cloudformation mapping.


Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - staging
      - production

Mappings:
  BasicParameterValue:
    Environment:
      staging: "staging"
      production: "production"

Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !FindInMap [BasicParameterValue, Environment, !Ref Environment]
      AllowedPattern: "^[a-zA-Z]+$"





