AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  cross-account

  A cross-account configuration stack using SSM Parameter Store

Globals:
  Function:
    Timeout: 20

Parameters:
  OtherAccountDeployRoleArns:
    Type: CommaDelimitedList
    Description: >
      Comma separated list of role ARNs in other accounts which are required to
      read some SSM parameters from this stack.

Outputs:
  FooBarParameterReadRoleARN:
    Description: The ARN for the role used to read the /Foo/Bar parameter
    Value: !GetAtt FooBarParameterReadRole.Arn

Resources:
  FooBarParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Foo/Bar
      Type: String
      Value: bar
      Tags:
        BillingOrganization: GDS
        BillingProgramme: One Login for Government
        BillingProject: Dev Platform
        BillingEnvironment: Demo
        Service: backend
        Name: FooBarParameter
        Source: alphagov/di-devplatform-demo-sam-app/cross-account/template.yaml

  FooBarParameterReadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref OtherAccountDeployRoleArns
            Action:
              - 'sts:AssumeRole'

      Policies:
        - PolicyName: ReadFooBarParameterPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Foo/Bar"
      Tags:
        - Key: BillingOrganization
          Value: GDS
        - Key: BillingProgramme
          Value: One Login for Government
        - Key: BillingProject
          Value: Dev Platform
        - Key: BillingEnvironment
          Value: Demo
        - Key: Service
          Value: backend
        - Key: Name
          Value: FooBarParameterReadRole
        - Key: Source
          Value: alphagov/di-devplatform-demo-sam-app/cross-account/template.yaml
