
AWSTemplateFormatVersion: "2010-09-09"
Description: "This template creates AWS Service Catalog Product"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Service Catalog Product Tags"
        Parameters:
          - AppName
          - Env
          - Dept
          - User
          - Owner
      - Label:
          default: "Service Catalog Portfolio Stack Name"
        Parameters:
          - ServiceCatalogPortfolioStackName
      - Label:
          default: "Service Catalog Product Details"
        Parameters:
          - SCProductName
          - SCProductDescription
          - SCProductOwner
          - SCProductSupport
          - SCProductDistributor
          - SCSupportEmail
          - SCSupportUrl
      - Label:
          default: "Service Catalog Portfolio Display Name"
        Parameters:
          - PortfolioDisplayName
      - Label:
          default: "Service Catalog Product Details"
        Parameters:
          - ProvisioningArtifactTemplateUrl
          - ProvisioningArtifactNameParameter
          - ProvisioningArtifactDescriptionParameter

Parameters:
  # Enviornment type
  Env:
    Description: Please specify the target Environment. Used for tagging and resource names. Mandatory LOWER CASE.
    Type: String
    Default: "dev"
    AllowedValues:
      - test
      - dev
      - prod

  # Application Name
  AppName:
    Description: Please specify the Application Name. Used for tagging and resource names. Mandatory LOWER CASE.
    Type: String
    Default: "app"

  # Department
  Dept:
    Description: Please specify the Department. Used for tagging
    Type: String
    Default: "1234"

  # User
  User:
    Description: Please specify the User. Used for tagging
    Type: String
    Default: "User"

  # Owner
  Owner:
    Description: Please specify the Owner. Used for tagging
    Type: String
    Default: "Owner"

  # Service Catalog Portfolio Stack Name
  ServiceCatalogPortfolioStackName:
    Description: Please specify the Service Catalog Portfolio Stack Name.
    Type: String
    Default: "service-catalog-poc"

  # ServiceCatalog Product Name
  SCProductName:
    Description: Please specify ServiceCatalog Product Name.
    Type: String
    Default: "ProductName"

  # ServiceCatalog Product Name Description
  SCProductDescription:
    Description: Please specify ServiceCatalog Product Name Description.
    Type: String
    Default: "ProductDescription"

  # ServiceCatalog Product Name Owner
  SCProductOwner:
    Description: Please specify ServiceCatalog Product Owner.
    Type: String
    Default: "ProductOwner"

  # ServiceCatalog Product Support
  SCProductSupport:
    Description: Please specify ServiceCatalog Product Support.
    Type: String
    Default: "IT Support can be reached @support"

  # ServiceCatalog Product Distributor
  SCProductDistributor:
    Description: Please specify ServiceCatalog Product Distributor.
    Type: String
    Default: "App Vendor"

  # ServiceCatalog Product Support Email
  SCSupportEmail:
    Description: Please specify ServiceCatalog Product Support Email.
    Type: String
    Default: "support@example.com"

  # ServiceCatalog Product Support URL
  SCSupportUrl:
    Description: Please specify ServiceCatalog Product Support URL.
    Type: String
    Default: "https://www.support.example.com"

  # ServiceCatalog Product S3 Bucket
  ProvisioningArtifactTemplateUrl:
    Description: Please specify the S3 URL of the template
    Type: String
    Default: "https://awsdocs.s3.amazonaws.com/servicecatalog/development-environment.template"
    #Default: "https://phillip-test.s3.eu-west-2.amazonaws.com/teamtemplates/sample1.template"

  # ServiceCatalog Product Artifact Name
  ProvisioningArtifactNameParameter:
    Description: Please specify ServiceCatalog Product Artifact Name.
    Type: String
    Default: "ProductExample"

  # ServiceCatalog Product Artifact Description
  ProvisioningArtifactDescriptionParameter:
    Description: Please specify ServiceCatalog Product Artifact Description.
    Type: String
    Default: "ProductExample"

Resources:
  ServiceCatalogCloudFormationProduct:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      Name: !Ref "SCProductName"
      Description: !Ref "SCProductDescription"
      Owner: !Ref "SCProductOwner"
      SupportDescription: !Ref "SCProductSupport"
      Distributor: !Ref "SCProductDistributor"
      SupportEmail: !Ref "SCSupportEmail"
      SupportUrl: !Sub "${SCSupportUrl}"
      Tags:
        - Key: Name
          Value: !Sub "${AppName}"
        - Key: App
          Value: !Sub "${AppName}"
        - Key: Dept
          Value: !Sub "${Dept}"
        - Key: Env
          Value: !Sub "${Env}"
        - Key: User
          Value: !Sub "${User}"
        - Key: Owner
          Value: !Sub "${Owner}"
      ProvisioningArtifactParameters:
        - Name: !Sub "${ProvisioningArtifactNameParameter}"
          Description: !Sub "${ProvisioningArtifactDescriptionParameter}"
          Info:
            LoadTemplateFromURL: !Sub "${ProvisioningArtifactTemplateUrl}"

  ServiceCatalogCloudFormationProduct1:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      Name: "Product 1"
      Description: "Product 1 description"
      Owner: "Dev Platform"
      SupportDescription: "Product 1 description"
      Distributor: "Dev Platform"
      SupportEmail: "dev-platform@example.com"
      SupportUrl: "https://www.support.example.com"
      Tags:
        - Key: Name
          Value: "Product 1"
        - Key: App
          Value: "Product 1"
        - Key: Dept
          Value: "Dev Platform"
        - Key: Env
          Value: "Dev Platform"
        - Key: User
          Value: "User"
        - Key: Owner
          Value: "Dev Platform"
      ProvisioningArtifactParameters:
        - Name:  "Product 1"
          Description: "Product 1 description"
          Info:
            LoadTemplateFromURL: "https://awsdocs.s3.amazonaws.com/servicecatalog/development-environment.template"

  ServiceCatalogCloudFormationProduct2:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      Name: "Product 2"
      Description: "Product 2 description"
      Owner: "Dev Platform"
      SupportDescription: "Product 2 description"
      Distributor: "Dev Platform"
      SupportEmail: "dev-platform@example.com"
      SupportUrl: "https://www.support.example.com"
      Tags:
        - Key: Name
          Value: "Product 2"
        - Key: App
          Value: "Product 2"
        - Key: Dept
          Value: "Dev Platform"
        - Key: Env
          Value: "Dev Platform"
        - Key: User
          Value: "User"
        - Key: Owner
          Value: "Dev Platform"
      ProvisioningArtifactParameters:
        - Name:  "Product 2"
          Description: "Product 2 description"
          Info:
            LoadTemplateFromURL: "https://awsdocs.s3.amazonaws.com/servicecatalog/development-environment.template"

  ServiceCatalogCloudFormationProduct3:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      Name: "Product 3"
      Description: "Product 3 description"
      Owner: "Dev Platform"
      SupportDescription: "Product 3 description"
      Distributor: "Dev Platform"
      SupportEmail: "dev-platform@example.com"
      SupportUrl: "https://www.support.example.com"
      Tags:
        - Key: Name
          Value: "Product 3"
        - Key: App
          Value: "Product 3"
        - Key: Dept
          Value: "Dev Platform"
        - Key: Env
          Value: "Dev Platform"
        - Key: User
          Value: "User"
        - Key: Owner
          Value: "Dev Platform"
      ProvisioningArtifactParameters:
        - Name:  "Product 3"
          Description: "Product 3 description"
          Info:
            #LoadTemplateFromURL: "https://awsdocs.s3.amazonaws.com/servicecatalog/development-environment.template"
            LoadTemplateFromURL: "https://phillip-test.s3.eu-west-2.amazonaws.com/teamtemplates/sample1.template?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEAkaCWV1LXdlc3QtMiJGMEQCIC7XkCd3yYzVWCR64IjMCbeyGNqCqL3q7MnyZM0oAIt1AiAA2yEfaWFt70TaA6FFriG%2FskDyOZL%2BL6dDTtNx78CGMiqLBAhyEAEaDDg0Mjc2Njg1NjQ2OCIMENpl263Ef5ZrfdYxKugD8j9IPiRrTDHqeVTOfdh6rTWPD4tsVTeJlZUXKdZpuR27B1ShCdi3iPGKveoBU1MkexQ9no61r%2Bv%2BFXx58KwdPo1HP27SogZPV6rm0GFv4u9kvFn%2BtvYF0bUU3HpyDw6lUQ0vNgBdw2xLFFTet%2Fyq86aHDM1j8SRHBsHxxwFbqxH3eMqWb%2FPBWjxi3AS9bFOrAiXVzDqle5Qk5EksBdYXhC1XshCoLH4Q7uNLW78jbdgYv5nJxUZzInkfy1Vp08msxth34c5CfasOqpO6Hh46iYwZJgrGS%2FtdJM6zF1SnXaMEdmLlXgLK1PblgpXYqgurRmylHUX5l10jqsFUhf1vKALU%2F6i3cfoRqs%2BHordXDjdMgdJDx2Ssj9Yse1FEhXy3N5Il5lfhrflfAQAsCZBuBvKJtdAg1m5mZLainj%2BLgkvSsYL8dibKmFJZTU6fu3TeX0eY4JmQ0QN6TUShMPMADNYTLlPy0IwB8bGCR8aP%2B%2BBGc4eDEzUHcBV74qO0yi1uaTOq2A%2FrVHQi9ev9790vXc1qD6DvrR%2Fffvx4tDugRskxbTBJXgXZ7l94JPmq6mOKtCzAeP7H%2FdEdX%2FU4ROxiaeLFcZT6o7kheIpf1r8ZYnYkPd02bm%2B2TXUOgLRjJj4C3Zv8gbl8wmsw7c27qwY6lQKumxrNGZ5gHG1xOIZHac%2FvB5Mq1veIA7dqHzhn0cVUrDaWzwdS9j8KKWCSxIUftNvhVdUgqFJAs%2FtpnPr75kxtKeJ1TGvVCpSLDm1%2BfA3561F2z7iN3v%2F3kvJ1wJji40x84jYp5KIZOpXfp3%2Bx0wJtcZO0LH%2FX433eQwyH4VvXXBzuYgsd3Uk%2BQMoCeGY8%2Bb6K4qyH6mjX9JycCqYUWjPQk2mmz3Q0IRlsAt3saO7UxTkGFzykPnW0UGUDx7TG17Cwm4MF5y9oU1BcAj7PQp%2B6CJFnbvNXi0EwQ2FMMsBkK2bnPy%2FaQ61GO4YbXaKQOa9N7aa8s4cXhoUgiX6vR1aoK5UaBORFqWhW6HnAakzQWcKVzgLW&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231205T091404Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=ASIA4IOGRWEKK3FU26GY%2F20231205%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Signature=a13db992ffff9803c025387bb9eec185bac243e234f18aa14f9a03173ee35a2a"

            #LoadTemplateFromURL: "https://github.com/govuk-one-login/devplatform-demo-sam-app/blob/071cc46341db50d7909aeaa813e499d8d537efdd/service-catalog/templates/dev-env.template"

  ServiceCatalogPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    DependsOn: ServiceCatalogCloudFormationProduct
    Properties:
      PortfolioId:
        Fn::ImportValue: !Sub "${ServiceCatalogPortfolioStackName}-ServiceCatalogPortfolio"
      ProductId: !Ref "ServiceCatalogCloudFormationProduct"

  ServiceCatalogCustomTagOptionsAssociation:
    Type: "AWS::ServiceCatalog::TagOptionAssociation"
    Properties:
      TagOptionId:
        Fn::ImportValue: !Sub "${ServiceCatalogPortfolioStackName}-ServiceCatalogProductTagOptions"
      ResourceId: !Ref "ServiceCatalogCloudFormationProduct"

Outputs:
  ServiceCatalogCloudFormationProductName:
    Value: !GetAtt "ServiceCatalogCloudFormationProduct.ProductName"
    Export:
      Name: !Sub "${AppName}-ServiceCatalogCloudFormationProductName"

  ServiceCatalogProvisioningArtifactIds:
    Value: !GetAtt "ServiceCatalogCloudFormationProduct.ProvisioningArtifactIds"
    Export:
      Name: !Sub "${AppName}-ServiceCatalogCloudFormationProvisioningArtifactIds"

  ServiceCatalogProvisioningArtifactNames:
    Value: !GetAtt "ServiceCatalogCloudFormationProduct.ProvisioningArtifactNames"
    Export:
      Name: !Sub "${AppName}-ServiceCatalogCloudFormationProvisioningArtifactNames"
#comment to rebuild
#comment to rebuild