
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates AWS Service Catalog Portfolio.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Service Catalog Portfolio Details"
        Parameters:
          - PortfolioDisplayName
          - PortfolioProviderName
          - PortfolioDescription
      -
        Label:
          default: "Service Catalog Portfolio Tags"
        Parameters:
          #- Name
          - Dept
          - Env
          - User
          - Owner
      -
        Label:
          default: "Service Catalog Product Tag Options Activation"
        Parameters:
          - ActivateProductTagOptions
      -
        Label:
          default: "Service Catalog Product Tag Options"
        Parameters:
          - ProductDept
      #     - ProductEnv
      #     - ProductUser
      #     - ProductOwner
      -
        Label:
          default: "Portfolio Sharing"
        Parameters:
          - ShareThisPortfolio
          - AccountIdOfChildAWSAccount

Parameters:

# Enviornment type
  Env:
    Description:    Please specify the target Environment. Used for tagging and resource names. Mandatory LOWER CASE.
    Type:           String
    Default:        "dev"
    AllowedValues:
      - test
      - dev
      - prod

# Department
  # Name:
  #   Description:    Please specify the Department Name Used for tagging
  #   Type:           String
  #   Default:        "1234"

# Department
  Dept:
    Description:    Please specify the Department. Used for tagging
    Type:           String
    Default:        "1234"

# User
  User:
    Description:    Please specify the User. Used for tagging
    Type:           String
    Default:        "User"

# Owner
  Owner:
    Description:    Please specify the Owner. Used for tagging
    Type:           String
    Default:        "Owner"

# Product Enviornment type
  # ProductEnv:
  #   Description:    Please specify the target Environment. Used for tagging and resource names. Mandatory LOWER CASE.
  #   Type:           String
  #   Default:        "dev"
  #   AllowedValues:
  #     - test
  #     - dev
  #     - prod

#Product Department
  ProductDept:
    Description:    Please specify the Department. Used for tagging
    Type:           String
    Default:        "1234"

# Product User
  # ProductUser:
  #   Description:    Please specify the User. Used for tagging
  #   Type:           String
  #   Default:        "User"

# Product Owner
  # ProductOwner:
  #   Description:    Please specify the Owner. Used for tagging
  #   Type:           String
  #   Default:        "Owner"

# Portfolio Provider Name
  PortfolioProviderName:
    Description:    Please specify the Portfolio Provider Name.
    Type:           String
    Default:        "devplatform-min"

# Portfolio Description
  PortfolioDescription:
    Description:    Please specify the Portfolio Description.
    Type:           String
    Default:        "Service Catalog Portfolio for Business Unit Dev-Ops"

# Portfolio Display Name
  PortfolioDisplayName:
    Description:    Please specify the Portfolio Description. Must satisfy regular expression pattern, (^[a-zA-Z0-9_\-]*)
    Type:           String
    Default:        "devplatform-min"

# Tag Options Activation
  ActivateProductTagOptions:
    Description:    Activate Custom Tag Options? Used for portfolio tagging
    Type:           String
    Default:        "true"
    AllowedValues:
      - 'true'
      - 'false'

# Share Portfolio
  ShareThisPortfolio:
    Description:    Please specify if this Portfolio will be Shared with additonal accounts?
    Type:           String
    Default:        "false"
    AllowedValues:
      - 'true'
      - 'false'

# AccountId
  AccountIdOfChildAWSAccount:
    Description:    Please specify the Sub AWS Account ID.
    Type:           String
    Default:        "1234567890"


Conditions:

  ConditionShareThisPortfolio: !Equals [ !Ref ShareThisPortfolio, 'true']

Resources:

  ServiceCatalogPortfolio:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties:
      ProviderName: !Ref 'PortfolioProviderName'
      Description: !Ref 'PortfolioDescription'
      DisplayName: !Ref 'PortfolioDisplayName'
      Tags:
        - Key:    Name
          Value:  !Sub '${PortfolioDisplayName}'
        - Key:    Dept
          Value:  !Sub '${Dept}'
        - Key:    Env
          Value:  !Sub '${Env}'
        - Key:    User
          Value:  !Sub '${User}'
        - Key:    Owner
          Value:  !Sub '${Owner}'

  ServiceCatalogPortfoliodevplatform-opt:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties:
      ProviderName: "devplatform-opt"
      Description: "devplatform-opt"
      DisplayName: "devplatform-opt"
      Tags:
        - Key:    Name
          Value:  !Sub '${PortfolioDisplayName}'
        - Key:    Dept
          Value:  !Sub '${Dept}'
        - Key:    Env
          Value:  !Sub '${Env}'
        - Key:    User
          Value:  !Sub '${User}'
        - Key:    Owner
          Value:  !Sub '${Owner}'

  ServiceCatalogProductTagOptions:
    Type: "AWS::ServiceCatalog::TagOption"
    Properties:
      Active:     !Ref 'ActivateProductTagOptions'
      Key:        Dept
      Value:      !Sub '${ProductDept}'
      # Key:        Env
      # Value:      !Sub '${ProductEnv}'
      # Key:        User
      # Value:      !Sub '${ProductUser}'
      # Key:        Owner
      # Value:      !Sub '${ProductOwner}'

  ServiceCatalogPortfolioShare:
    Type: "AWS::ServiceCatalog::PortfolioShare"
    Condition: ConditionShareThisPortfolio
    Properties:
      AccountId: !Ref 'AccountIdOfChildAWSAccount'
      PortfolioId: !Ref 'ServiceCatalogPortfolio'

# Accepts portfolio share - not sure if needed yet
#   ServiceCatalogAcceptPortfolioShare:
#      Type: AWS::ServiceCatalog::AcceptedPortfolioShare
#      Properties:
#        AcceptLanguage: String
#        PortfolioId: String

Outputs:

  ServiceCatalogPortfolio:
    Value:    !Ref 'ServiceCatalogPortfolio'
    Export:
      Name:   !Sub '${AWS::StackName}-ServiceCatalogPortfolio'

  ServiceCatalogPortfolioName:
    Value:    !GetAtt 'ServiceCatalogPortfolio.PortfolioName'
    Export:
      Name:   !Sub '${AWS::StackName}-ServiceCatalogPortfolioName'

  ServiceCatalogProductTagOptions:
    Value:    !Ref 'ServiceCatalogProductTagOptions'
    Export:
      Name:   !Sub '${AWS::StackName}-ServiceCatalogProductTagOptions'