
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates AWS Service Catalog Portfolio.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Service Catalog Product Tag Options Activation"
        Parameters:
          - ActivateProductTagOptions
      - Label:
          default: "Service Catalog Product Tag Options"
        Parameters:
          - ProductDept
      #     - ProductEnv
      #     - ProductUser
      #     - ProductOwner
      - Label:
          default: "Portfolio Sharing"
        Parameters:
          - ShareThisPortfolio
          - AccountIdOfChildAWSAccount

      - Label:
          default: "Service Catalog Product Tags"
        Parameters:
          - AppName
          - Env
          - Dept
          - User
          - Owner



####################################
# Parameters
####################################
Parameters:

  S3BucketUrl:
    Description:    Please specify the S3 Bucket name.
    Type:           String
    Default:        "template-bucket-templatebucket-35qbug5k1irh.s3.eu-west-2.amazonaws.com"

# Enviornment type
  Env:
    Description:    Please specify the target Environment. Used for tagging and resource names. Mandatory LOWER CASE.
    Type:           String
    Default:        "dev"
    AllowedValues:
      - test
      - dev
      - prod

# Department
  # Name:
  #   Description:    Please specify the Department Name Used for tagging
  #   Type:           String
  #   Default:        "1234"

# Department
  Dept:
    Description:    Please specify the Department. Used for tagging
    Type:           String
    Default:        "1234"

# User
  User:
    Description:    Please specify the User. Used for tagging
    Type:           String
    Default:        "User"

# Owner
  Owner:
    Description:    Please specify the Owner. Used for tagging
    Type:           String
    Default:        "Owner"

# Product Enviornment type
  # ProductEnv:
  #   Description:    Please specify the target Environment. Used for tagging and resource names. Mandatory LOWER CASE.
  #   Type:           String
  #   Default:        "dev"
  #   AllowedValues:
  #     - test
  #     - dev
  #     - prod

#Product Department
  ProductDept:
    Description:    Please specify the Department. Used for tagging
    Type:           String
    Default:        "1234"


# Tag Options Activation
  ActivateProductTagOptions:
    Description:    Activate Custom Tag Options? Used for portfolio tagging
    Type:           String
    Default:        "true"
    AllowedValues:
      - 'true'
      - 'false'

# Share Portfolio
  ShareThisPortfolio:
    Description:    Please specify if this Portfolio will be Shared with additonal accounts?
    Type:           String
    Default:        "true"
    AllowedValues:
      - 'true'
      - 'false'

# AccountId
  AccountIdOfChildAWSAccount:
    Description:    Please specify the Sub AWS Account ID.
    Type:           String
    Default:        "123456789012"

# Application Name
  AppName:
    Description: Please specify the Application Name. Used for tagging and resource names. Mandatory LOWER CASE.
    Type: String
    Default: "app"

####################################
# Conditions
####################################
Conditions:
  ConditionShareThisPortfolio: !Equals [ !Ref ShareThisPortfolio, 'true']

####################################
# Resources
####################################
Resources:

  SCPortfolioBaseAccount:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: "Base AWS account"
      Description: "base aws account"
      DisplayName: "base aws account"

  SCPortfolioFrontend:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: "Frontend team"
      Description: "Frontend team"
      DisplayName: "Frontend team"
  


  SCPProductTagOptions:
    Type: AWS::ServiceCatalog::TagOption
    Properties:
      Active:     !Ref ActivateProductTagOptions
      Key:        Dept
      Value:      !Sub '${ProductDept}'
      # Key:        Env
      # Value:      !Sub '${ProductEnv}'
      # Key:        User
      # Value:      !Sub '${ProductUser}'
      # Key:        Owner
      # Value:      !Sub '${ProductOwner}'

  # Share Portfolio with an AWS account
  # ServiceCatalogPortfolioShare:
  #   Type: AWS::ServiceCatalog::PortfolioShare
  #   Condition: ConditionShareThisPortfolio
  #   Properties:
  #     AccountId: !Ref AccountIdOfChildAWSAccount
  #     PortfolioId: !Ref ServiceCatalogPortfolio1

  # Accepts portfolio share - not sure if needed yet
  # ServiceCatalogAcceptPortfolioShare:
  #    Type: AWS::ServiceCatalog::AcceptedPortfolioShare
  #    Properties:
  #      AcceptLanguage: String
  #      PortfolioId: String

  SCCProduct1:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "vpc"
      Description: "VPC and networking resources template"
      Owner: "Product x owner"
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${AppName}"
      #   - Key: App
      #     Value: !Sub "${AppName}"
      ProvisioningArtifactParameters:
        - Name: "ProvisioningArtifactNameParameter"
          Description: "ProvisioningArtifactDescriptionParameter"
          Info:
            LoadTemplateFromURL: !Sub "https://${S3BucketUrl}/vpc/template.yaml"

  SCCProduct2:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "signer"
      Description: "AWS Signer Signing Profile template"
      Owner: "Product x owner"
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${AppName}"
      #   - Key: App
      #     Value: !Sub "${AppName}"
      ProvisioningArtifactParameters:
        - Name: "ProvisioningArtifactNameParameter"
          Description: "ProvisioningArtifactDescriptionParameter"
          Info:
            LoadTemplateFromURL: !Sub "https://${S3BucketUrl}/signer/template.yaml"

 
  SCCProduct3:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "alerting-integration"
      Description: "Stack to create an SNS topic with external API subscriptions such as PagerDuty"
      Owner: "Product x owner"
      # SupportDescription: "Description"
      # Distributor: "distributor"
      # SupportEmail: "email@exmaple.com"
      # SupportUrl: "https://bbc.co.uk"
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${AppName}"
      #   - Key: App
      #     Value: !Sub "${AppName}"
      ProvisioningArtifactParameters:
        - Name: "ProvisioningArtifactNameParameter"
          Description: "ProvisioningArtifactDescriptionParameter"
          Info:
            LoadTemplateFromURL: !Sub "https://${S3BucketUrl}/alerting-integration/template.yaml"

  SCCProduct4:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "container-signer"
      Description: "Container Signer KMS Key template managed by dev-platform"
      Owner: "Product x owner"
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${AppName}"
      #   - Key: App
      #     Value: !Sub "${AppName}"
      ProvisioningArtifactParameters:
        - Name: "ProvisioningArtifactNameParameter"
          Description: "ProvisioningArtifactDescriptionParameter"
          Info:
            LoadTemplateFromURL: !Sub "https://${S3BucketUrl}/container-signer/template.yaml"

  SCCProduct5:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "api-gateway-logs"
      Description: "Stack to setup accounts that use API Gateway logging. Managed by dev-platform."
      Owner: "Product x owner"
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${AppName}"
      #   - Key: App
      #     Value: !Sub "${AppName}"
      ProvisioningArtifactParameters:
        - Name: "ProvisioningArtifactNameParameter"
          Description: "ProvisioningArtifactDescriptionParameter"
          Info:
            LoadTemplateFromURL: !Sub "https://${S3BucketUrl}/api-gateway-logs/template.yaml"

  SCPortfolioProductAssociation1:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    # DependsOn: ServiceCatalogCloudFormationProduct
    Properties:
      PortfolioId: !Ref SCPortfolioBaseAccount
      ProductId: !Ref SCCProduct1

  SCPortfolioProductAssociation2:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    # DependsOn: ServiceCatalogCloudFormationProduct
    Properties:
      PortfolioId: !Ref SCPortfolioBaseAccount
      ProductId: !Ref SCCProduct2

  SCPortfolioProductAssociation3:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    # DependsOn: ServiceCatalogCloudFormationProduct
    Properties:
      PortfolioId: !Ref SCPortfolioBaseAccount
      ProductId: !Ref SCCProduct3

  SCPortfolioProductAssociation4:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    # DependsOn: ServiceCatalogCloudFormationProduct
    Properties:
      PortfolioId: !Ref SCPortfolioBaseAccount
      ProductId: !Ref SCCProduct4

  SCPortfolioProductAssociation5:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    # DependsOn: ServiceCatalogCloudFormationProduct
    Properties:
      PortfolioId: !Ref SCPortfolioFrontend
      ProductId: !Ref SCCProduct5
      

  # SCCustomTagOptionsAssociation:
  #   Type: AWS::ServiceCatalog::TagOptionAssociation
  #   Properties:
  #     TagOptionId: !Ref ServiceCatalogProductTagOptions
  #     ResourceId: !Ref ServiceCatalogCloudFormationProduct


####################################
# Outputs
####################################
# Outputs:

# 