AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creating SSM parameters based on ENVs using cloudformation mapping.


Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - staging
      - production

  BasicParamValue:
    Type: String


Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref BasicParamValue
      AllowedPattern: "^[a-zA-Z]+$"




