AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sam-app2.
  Managed by dev-platform

Parameters:
  CodeSigningConfigArn:
    Type: String
    Description: Asserts that lambdas are signed when deployed.
    Default: "none"

  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"

  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"

Conditions:
  IsNonDevEnvironment:
    Fn::Not:
      - Fn::Or:
        - Fn::Equals:
          - !Ref Environment
          - "dev"
        - Fn::Equals:
          - !Ref Environment
          - "demo"
        - Fn::Equals:
          - !Ref Environment
          - "local"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

Mappings:
  EnvironmentConfiguration:
    dev:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables   # pragma: allowlist secret
    build:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables   # pragma: allowlist secret
    staging:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables   # pragma: allowlist secret
    integration:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables   # pragma: allowlist secret
    production:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables      # pragma: allowlist secret

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    Timeout: 20
    Environment:
      Variables:
        AWS_LAMBDA_EXEC_WRAPPER: /opt/dynatrace
        DT_CONNECTION_AUTH_TOKEN:
          !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}'           # pragma: allowlist secret
            - SecretArn: !FindInMap [ EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn ]
        DT_CONNECTION_BASE_URL:
          !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}'             # pragma: allowlist secret
            - SecretArn: !FindInMap [ EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn ]
        DT_CLUSTER_ID:
          !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}'                      # pragma: allowlist secret
            - SecretArn: !FindInMap [ EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn ]
        DT_LOG_COLLECTION_AUTH_TOKEN:
          !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}'       # pragma: allowlist secret
            - SecretArn: !FindInMap [ EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn ]
        DT_TENANT:
          !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}'                          # pragma: allowlist secret
            - SecretArn: !FindInMap [ EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn ]
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: "true"
    # https://govukverify.atlassian.net/wiki/spaces/Architecture/pages/3521183835/ADR+0082+Run+Lambda+functions+on+arm64+processor+architecture
    Architectures:
      - arm64
    Layers:
      - !Sub
        - '{{resolve:secretsmanager:${SecretArn}:SecretString:JAVA_LAYER}}'                             # pragma: allowlist secret
        - SecretArn: !FindInMap [ EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn ]


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      # checkov:skip=CKV_AWS_116: DLQ not required
      # checkov:skip=CKV_AWS_117: Internet access not required
    Metadata:
      checkov:
        skip:
          - id: "CKV_AWS_116"
            comment: "DLQ not required"
          - id: "CKV_AWS_117"
            comment: "Internet access not required"
    Properties:
      CodeUri: HelloWorldFunction
      AutoPublishAlias: LatestVersion
      Handler: helloworld.App::handleRequest
      Runtime: java11
      MemorySize: 2048
      ReservedConcurrentExecutions: 5
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref HelloWorldRestApi
      Tags:
        Product: GOV.UK Sign In
        System: Dev Platform
        Environment: Demo
        Service: backend
        Name: HelloWorldFunction
        Source: govuk-one-login/devplatform-demo-sam-app/sam-app2/template.yaml
        CheckovRulesToSkip: CKV_AWS_116.CKV_AWS_117

  APIGatewayAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      KmsKeyId: !GetAtt HelloWorldKmsKey.Arn
      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Dev Platform
        - Key: Environment
          Value: Demo
        - Key: Service
          Value: backend
        - Key: Name
          Value: APIGatewayAccessLogGroup
        - Key: Source
          Value: govuk-one-login/devplatform-demo-sam-app/sam-app2/template.yaml

  # Setup to validate we can use pipelines to set CSLS as the destination: https://github.com/alphagov/centralised-security-logging-service
  CSLSFirehoseSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Condition: IsNonDevEnvironment
    Properties:
      DestinationArn: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython
      FilterPattern: ""
      LogGroupName: !Ref APIGatewayAccessLogGroup

  HelloWorldRestApi:
    Type: AWS::Serverless::Api
    # checkov:skip=CKV_AWS_120:API caching is not the programme approved way
    Metadata:
      checkov:
        skip:
          - id: "CKV_AWS_120"
            comment: "API caching is not the programme approved way"
    Properties:
      OpenApiVersion: 3.0.3
      StageName: Prod
      AccessLogSetting:
        Format: "$context.requestId $context.httpMethod $context.path"
        DestinationArn: !GetAtt APIGatewayAccessLogGroup.Arn
      CacheClusterEnabled: false
      # CacheClusterSize: "0.5"
      TracingEnabled: true
      Tags:
        Product: GOV.UK Sign In
        System: Dev Platform
        Environment: Demo
        Service: backend
        Name: HelloWorldRestApi
        Source: govuk-one-login/devplatform-demo-sam-app/sam-app2/template.yaml

  AutoScalingHelloWorldScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    # Need to depend on the auto deployed version alias: "<function_logical_id> + Alias + <the_alias_name>"
    DependsOn: HelloWorldFunctionAliasLatestVersion
    Properties:
      MaxCapacity: 3
      MinCapacity: 1
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency"
      ServiceNamespace: lambda
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ResourceId: !Join
        - ':'
        - - 'function'
          - !Select [ 6, !Split [ ':', !GetAtt HelloWorldFunction.Arn ] ]
          - 'LatestVersion'

  HelloWorldLambdaAutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: AutoScalingHelloWorldScalableTarget
    Properties:
      PolicyName: "hello-world-lambda-autoscaling-policy"
      PolicyType: TargetTrackingScaling
      ResourceId: !Join
        - ':'
        - - 'function'
          - !Select [ 6, !Split [ ':', !GetAtt HelloWorldFunction.Arn ] ]
          - 'LatestVersion'
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization
        TargetValue: 0.7

  HelloWorldKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: 'kms:*'
            Resource: '*'
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Dev Platform
        - Key: Environment
          Value: Demo
        - Key: Service
          Value: backend
        - Key: Name
          Value: HelloWorldKmsKey
        - Key: Source
          Value: govuk-one-login/devplatform-demo-sam-app/sam-app2/template.yaml

  HelloWaf:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Block: {}
      Scope: "REGIONAL"
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: "hello-waf-metric"
        SampledRequestsEnabled: true
      Rules:
        # Optional rule set to restrict to GDS IP addresses.
        # See WAFv2GDSIPSet resource further on.
        - Name: GDSIPs
          Action:
            Allow: {}
          Priority: 10
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt WAFv2GDSIPSet.Arn
              IPSetForwardedIPConfig:
                FallbackBehavior: MATCH
                HeaderName: X-Forwarded-For
                Position: FIRST
          VisibilityConfig:
            CloudWatchMetricsEnabled: TRUE
            MetricName: !Sub "${AWS::StackName}-WAFGDSIP-hits"
            SampledRequestsEnabled: FALSE
        - Name: AWS-AWMManagedRuleCommonRuleSet
          OverrideAction:
            None: {}
          Priority: 20
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesCommonRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: TRUE
            MetricName: !Sub "${AWS::StackName}-AWSCRS-hits"
            SampledRequestsEnabled: FALSE
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 30
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: TRUE
            MetricName: !Sub "${AWS::StackName}-AWSKBI-hits"
            SampledRequestsEnabled: FALSE

# The IP address blocks below are referenced from here:
# https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/working-at-gds/gds-internal-it/gds-internal-it-network-public-ip-addresses
  WAFv2GDSIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Addresses:
        - "213.86.153.211/32"
        - "213.86.153.212/32"
        - "213.86.153.213/32"
        - "213.86.153.214/32"
        - "213.86.153.231/32"
        - "213.86.153.235/32"
        - "213.86.153.236/32"
        - "213.86.153.237/32"
        - "51.149.8.0/25"
        - "51.149.8.128/29"
      IPAddressVersion: IPV4
      Scope: REGIONAL
      Tags:
        - Key: Product
          Value: GOV.UK Sign In
        - Key: System
          Value: Dev Platform
        - Key: Environment
          Value: Demo
        - Key: Service
          Value: backend
        - Key: Name
          Value: !Sub "${AWS::StackName}-WAFv2GDSIPSet"
        - Key: Source
          Value: govuk-one-login/devplatform-demo-sam-app/sam-app2/template.yaml

  HelloWafGatewayAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${HelloWorldRestApi}/stages/${HelloWorldRestApi.Stage}"
      WebACLArn: !GetAtt HelloWaf.Arn

  HelloWafLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - '-'
          - - aws-waf-logs-
            - Ref: AWS::StackName
            - Fn::Select:
                - 4
                - Fn::Split:
                    - '-'
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - Ref: AWS::StackId
      RetentionInDays: 30
      KmsKeyId: !GetAtt HelloWorldKmsKey.Arn
      Tags:
        - Key: Service
          Value: backend
        - Key: Name
          Value: HelloWafLogGroup
        - Key: Source
          Value: govuk-one-login/devplatform-demo-sam-app/sam-app2/template.yaml

  HelloWafLogs:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      LogDestinationConfigs:
        - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${HelloWafLogGroup}"
      ResourceArn: !GetAtt HelloWaf.Arn

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${HelloWorldRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
