name: Create Release with Python Script

on:
  workflow_dispatch:
    inputs:
      dry_run:
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: PSREDEV-2337

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Install semantic-version
        run: pip install semantic-version

      - name: Create Release and Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: python .github/scripts/create_release.py