name: Create Release with gh CLI

on:
  push:
    branches:
      - PSREDEV-2337  # Or your desired branch

jobs:
  validate-access:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository access
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }} | grep -q "full_name"
          if [ $? -eq 0 ]; then
            echo "Repository access granted."
            exit 0
          else
            echo "Error: Repository access denied."
            exit 1
          fi