name: Create Release with Python Script

on:
  push:
    branches:
      - cg-test

      permissions:
  actions: read
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: cg-test

      - name: Get SHA
        id: get_sha
        run: |
          git fetch origin cg-test
          echo "::set-output name=sha::$(git rev-parse FETCH_HEAD)"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Create Release and Tag
        env:
          RELEASE_CREATION_POC: ${{ secrets.RELEASE_CREATION_POC }}
          TARGET_SHA: ${{ steps.get_sha.outputs.sha }}
        #run: python .github/scripts/get_commits.py  
        run: python .github/scripts/create_release.py