name: Monorepo Release

on:
  push:
    branches:
      - PSREDEV-2337  # Your default branch

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: PSREDEV-2337

      - name: Run release script
        run: |
          ./create_gh_release_monorepo.sh
      #- name: Push tags
      #  run: git push origin --tags