name: Luke testing basic app

on:
    workflow_dispatch:
    push:
      branches:
        - luke_test

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - run: ls
      - uses: actions/checkout@v4
      - run: ls
      - name: Hello World
        run: echo "Hello World"