name: Node server build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Upload to ECR and tag
        uses: alphagov/di-devplatform-upload-action-ecr@5f34e3853fd8078a092061aedfa98b3c95ced8c7
        with:
          role-to-assume-arn: ${{ secrets.NODE_ROLE_TO_ASSUME }}
          
          working-directory: node
          ecr-repo-name: ${{ secrets.ECR_REPOSITORY }}
          artifact-bucket-name: ${{ secrets.NODE_ARTIFACT_BUCKET }}