name: Node with waf for fraud function test build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./node-with-waf

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Upload to ECR and tag
        uses: govuk-one-login/devplatform-upload-action-ecr@v1.3.0
        with:
          role-to-assume-arn: ${{ secrets.NODE_WITH_WAF_FRAUD_TEST_ROLE_TO_ASSUME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_FRAUD_TEST_KMS_KEY }}
          working-directory: node-with-waf
          ecr-repo-name: ${{ secrets.NODE_WITH_WAF_FRAUD_TEST_ECR_REPOSITORY }}
          artifact-bucket-name: ${{ secrets.NODE_WITH_WAF_FRAUD_TEST_ARTIFACT_BUCKET }}