name: Node server build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./node

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Upload to ECR and tag
        uses: govuk-one-login/devplatform-upload-action-ecr@1.1.0
        with:
          role-to-assume-arn: ${{ secrets.NODE_ROLE_TO_ASSUME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          working-directory: node
          ecr-repo-name: ${{ secrets.ECR_REPOSITORY }}
          artifact-bucket-name: ${{ secrets.NODE_ARTIFACT_BUCKET }}