name: Node server build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "node/**"
      - ".github/workflows/node-post-merge-actions.yml"

defaults:
  run:
    shell: bash
    working-directory: ./node

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.NODE_ROLE_TO_ASSUME }}
          aws-region: eu-west-2

      - name: Build, tag, and push testing image to Amazon ECR
        uses: govuk-one-login/devplatform-upload-action-ecr@v1.4.0
        with:
          role-to-assume-arn: ${{ secrets.NODE_ROLE_TO_ASSUME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          build-and-push-image-only: true
          working-directory: node/tests/traffic-test
          artifact-bucket-name: ${{ secrets.NODE_ARTIFACT_BUCKET }}
          ecr-repo-name: ${{ secrets.TRAFFIC_ECR_REPOSITORY }}
          checkout-repo: false
          push-latest-tag: true

      - name: Build, tag, and push post-deployment testing image to Amazon ECR
        uses: govuk-one-login/devplatform-upload-action-ecr@v1.4.0
        with:
          role-to-assume-arn: ${{ secrets.NODE_ROLE_TO_ASSUME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          build-and-push-image-only: true
          working-directory: node/tests/post-deployment-test
          artifact-bucket-name: ${{ secrets.NODE_ARTIFACT_BUCKET }}
          ecr-repo-name: ${{ secrets.TEST_ECR_REPOSITORY }}
          checkout-repo: false
          push-latest-tag: true

      - name: Upload to ECR and tag
        uses: govuk-one-login/devplatform-upload-action-ecr@v1.4.0
        with:
          role-to-assume-arn: ${{ secrets.NODE_ROLE_TO_ASSUME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          working-directory: node
          ecr-repo-name: ${{ secrets.ECR_REPOSITORY }}
          artifact-bucket-name: ${{ secrets.NODE_ARTIFACT_BUCKET }}
          private-docker-registry: khw46367.live.dynatrace.com
          private-docker-login-username: khw46367
          private-docker-login-password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
